# Generated by Django 4.2.1 on 2023-05-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('personal_tax_number', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Tax number')),
                ('account', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
    ]
